[tool.poetry]
name = "ruff-config-generator"
version = "0.1.0-dev"
description = "Generates ruff default configuration"
authors = ["KRunchPL <krunchfrompoland@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/KRunchPL/ruff-config-generator"
repository = "https://github.com/KRunchPL/ruff-config-generator"
documentation = "https://github.com/KRunchPL/ruff-config-generator"
license = "Apache-2.0"
packages = [
    { include = "ruff_config_generator" },
]

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.31.0"
beautifulsoup4 = "^4.12.3"

[tool.poetry.group.dev.dependencies]
darglint = "^1.8.1"
flake8 = "^7.0.0"
ruff = "^0.2.1"
mypy = "^1.8.0"
pytest = "^8.0.0"
pytest-cov = "^4.1.0"
pytest-mock = "^3.12.0"
types-requests = "^2.31.0.20240125"
types-beautifulsoup4 = "^4.12.0.20240106"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
