[project]
name = "ruff-config-generator"
dynamic = ["version"]
description = "Generates ruff configuration"
authors = [{ name = "KRunchPL", email = "krunchfrompoland@gmail.com" }]
license = "Apache-2.0"
readme = "README.md"
requires-python = ">=3.14,<4.0"
dependencies = [
    "loguru >=0.7.3,<0.8.0",
    "beautifulsoup4 >=4.15.0,<5.0.0",
    "pydantic >=2.13.4,<3.0.0",
    "requests >=2.32.5,<3.0.0",
    "typer>=0.27.0,<0.28.0",
    "typer-config>=1.5.1,<2.0.0",
]

[dependency-groups]
dev = [
    "flake8",
    "mypy",
    "pydoclint",
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "ruff",
    "logot[loguru]",
    "types-beautifulsoup4",
    "types-requests",
]

[project.urls]
homepage = "https://github.com/KRunchPL/ruff-config-generator"
repository = "https://github.com/KRunchPL/ruff-config-generator"
documentation = "https://github.com/KRunchPL/ruff-config-generator"

[project.scripts]
ruff-config-generator = "ruff_config_generator.__main__:app"
ruff_config_generator = "ruff_config_generator.__main__:app"

[tool.hatch.build.targets.wheel]
packages = ["src/ruff_config_generator"]

[tool.hatch.version]
scheme = "semver"
path = "version.txt"
pattern = "(?P<version>.*)"

[build-system]
requires = ["hatchling", "hatch-semver"]
build-backend = "hatchling.build"

[tool.uv]
system-certs = true
