workdir = "workdir"
settings_html_file_name = 'settings.html'
rules_html_file_name = 'rules.html'
version_file_name = 'version.txt'
default_values_file_name = 'default.toml'
adjusted_values_file_name = 'adjusted.toml'

[overrides.analyze]
direction = 'Dependencies'
