name: PR checker

on: [push, pull_request]

jobs:
  lint_and_unittest:
    name: Run linter, type checking and unit tests
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        poetry-version: ["1.8.2"]
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Poetry ${{ matrix.poetry-version }}
      run: |
        python -m pip install poetry==${{ matrix.poetry-version }}
        poetry config virtualenvs.create false
    - name: Install package with dependencies
      run: poetry install --no-root
    - name: Linter
      run: |
        ruff check .
        flake8
        ruff format .
        git diff-index --quiet HEAD -- || (echo "The following files must be ruff formatted:"; git diff --name-only; exit 1)
    - name: Typing checker
      run: mypy
    - name: Unit tests
      run: pytest
